-- FFXI food item lookup for Ashita v4, keyed by item id.
-- Generated from Windower Resources (items.lua + item_descriptions.lua):
-- category=="Usable" AND description contains a food-effect signature.
--   food     = grants a standard food buff
--   crafting = rusks & macarons (synthesis buffs)
--   petfood  = BST Pet Food (used via Reward)
-- Usage: local food = require('food_items'); local e = food[itemId];

return {
    [4235] = { name = "Cursed Soup", class = "food" },
    [4266] = { name = "Fulm-long Sub", class = "food" },
    [4267] = { name = "Btr. Nebimonite", class = "food" },
    [4268] = { name = "Sea Spray Risotto", class = "food" },
    [4269] = { name = "Bijou Glace", class = "food" },
    [4270] = { name = "Swt. Rice Cake", class = "food" },
    [4271] = { name = "Rice Dumpling", class = "food" },
    [4276] = { name = "Flint Caviar", class = "food" },
    [4277] = { name = "Tonosama R.Ball", class = "food" },
    [4278] = { name = "Shogun R.Ball", class = "food" },
    [4279] = { name = "Tavnazian Salad", class = "food" },
    [4280] = { name = "G. Cracker +1", class = "food" },
    [4281] = { name = "Red Hot Cracker", class = "food" },
    [4282] = { name = "Pipin' Popoto", class = "food" },
    [4284] = { name = "Tender Navarin", class = "food" },
    [4285] = { name = "Ocean Soup", class = "food" },
    [4286] = { name = "Healing Tea", class = "food" },
    [4287] = { name = "Opo-opo Tart", class = "food" },
    [4292] = { name = "Pain de Neige", class = "food" },
    [4293] = { name = "Monastic Saute", class = "food" },
    [4294] = { name = "Medicinal Quus", class = "food" },
    [4295] = { name = "Royal Saute", class = "food" },
    [4296] = { name = "Green Curry", class = "food" },
    [4297] = { name = "Black Curry", class = "food" },
    [4298] = { name = "Red Curry", class = "food" },
    [4299] = { name = "Orange au Lait", class = "food" },
    [4300] = { name = "Apple au Lait", class = "food" },
    [4301] = { name = "Pear au Lait", class = "food" },
    [4303] = { name = "Persikos au Lait", class = "food" },
    [4320] = { name = "Apple Pie +1", class = "food" },
    [4321] = { name = "T. Timbers Salad", class = "food" },
    [4322] = { name = "Dhalmel Pie +1", class = "food" },
    [4323] = { name = "Vegetable Broth", class = "food" },
    [4324] = { name = "Hob. Chocolate", class = "food" },
    [4325] = { name = "Hobgoblin Pie", class = "food" },
    [4326] = { name = "Frog Flambe", class = "food" },
    [4327] = { name = "Emerald Soup", class = "food" },
    [4328] = { name = "Hobgoblin Bread", class = "food" },
    [4329] = { name = "Newt Flambe", class = "food" },
    [4330] = { name = "Witch Risotto", class = "food" },
    [4331] = { name = "Imperial Omelette", class = "food" },
    [4332] = { name = "Orange Kuchen +1", class = "food" },
    [4333] = { name = "Witch Soup", class = "food" },
    [4334] = { name = "Grilled Corn", class = "food" },
    [4335] = { name = "Juicy Mutton", class = "food" },
    [4336] = { name = "Swt. Bkd. Apple", class = "food" },
    [4337] = { name = "Stamina Soup", class = "food" },
    [4339] = { name = "Rolan. Pie +1", class = "food" },
    [4340] = { name = "Optical Soup", class = "food" },
    [4341] = { name = "Sunset Soup", class = "food" },
    [4342] = { name = "Steamed Crab", class = "food" },
    [4343] = { name = "Witch Kabob", class = "food" },
    [4344] = { name = "Witch Stew", class = "food" },
    [4345] = { name = "Flnd. Meuniere +1", class = "food" },
    [4346] = { name = "Bass Meuniere +1", class = "food" },
    [4347] = { name = "Slmn. Meuniere +1", class = "food" },
    [4348] = { name = "Mttn. Enchilada", class = "food" },
    [4349] = { name = "Bunny Ball", class = "food" },
    [4350] = { name = "Dragon Steak", class = "food" },
    [4353] = { name = "Sea Bass Croute", class = "food" },
    [4355] = { name = "Salmon Sub", class = "food" },
    [4356] = { name = "White Bread", class = "food" },
    [4364] = { name = "Black Bread", class = "food" },
    [4371] = { name = "Grilled Hare", class = "food" },
    [4376] = { name = "Meat Jerky", class = "food" },
    [4378] = { name = "Selbina Milk", class = "food" },
    [4380] = { name = "Smoked Salmon", class = "food" },
    [4381] = { name = "Meat Mithkabob", class = "food" },
    [4391] = { name = "Bretzel", class = "food" },
    [4393] = { name = "Orange Kuchen", class = "food" },
    [4394] = { name = "Ginger Cookie", class = "food" },
    [4395] = { name = "Galkan Sausage", class = "food" },
    [4396] = { name = "Sausage Roll", class = "food" },
    [4397] = { name = "Cinna-cookie", class = "food" },
    [4398] = { name = "Fish Mithkabob", class = "food" },
    [4404] = { name = "Roast Trout", class = "food" },
    [4405] = { name = "Rice Ball", class = "food" },
    [4406] = { name = "Baked Apple", class = "food" },
    [4407] = { name = "Carp Sushi", class = "food" },
    [4408] = { name = "Tortilla", class = "food" },
    [4409] = { name = "Hard-boiled Egg", class = "food" },
    [4410] = { name = "Roast Mushroom", class = "food" },
    [4411] = { name = "Dhalmel Pie", class = "food" },
    [4413] = { name = "Apple Pie", class = "food" },
    [4414] = { name = "Rolanberry Pie", class = "food" },
    [4415] = { name = "Roasted Corn", class = "food" },
    [4416] = { name = "Pea Soup", class = "food" },
    [4417] = { name = "Egg Soup", class = "food" },
    [4418] = { name = "Turtle Soup", class = "food" },
    [4419] = { name = "Mushroom Soup", class = "food" },
    [4420] = { name = "Tomato Soup", class = "food" },
    [4421] = { name = "Melon Pie", class = "food" },
    [4422] = { name = "Orange Juice", class = "food" },
    [4424] = { name = "Melon Juice", class = "food" },
    [4430] = { name = "Pumpkin Soup", class = "food" },
    [4433] = { name = "Dhalmel Stew", class = "food" },
    [4434] = { name = "Mushroom Risotto", class = "food" },
    [4436] = { name = "Baked Popoto", class = "food" },
    [4437] = { name = "Roast Mutton", class = "food" },
    [4438] = { name = "Dhalmel Steak", class = "food" },
    [4439] = { name = "Navarin", class = "food" },
    [4440] = { name = "Whitefish Stew", class = "food" },
    [4446] = { name = "Pumpkin Pie", class = "food" },
    [4452] = { name = "Shark Fin Soup", class = "food" },
    [4453] = { name = "Eyeball Soup", class = "food" },
    [4456] = { name = "Boiled Crab", class = "food" },
    [4457] = { name = "Eel Kabob", class = "food" },
    [4458] = { name = "Goblin Bread", class = "food" },
    [4459] = { name = "Nebimonite Bake", class = "food" },
    [4460] = { name = "Stone Cheese", class = "food" },
    [4465] = { name = "Goblin Stew", class = "food" },
    [4466] = { name = "Spicy Cracker", class = "food" },
    [4467] = { name = "Garlic Cracker", class = "food" },
    [4487] = { name = "Colored Egg", class = "food" },
    [4488] = { name = "Jack-o'-Lantern", class = "food" },
    [4489] = { name = "Vegetable Gruel", class = "food" },
    [4490] = { name = "Pickled Herring", class = "food" },
    [4492] = { name = "Puls", class = "food" },
    [4493] = { name = "Windurstian Tea", class = "food" },
    [4494] = { name = "San d'Orian Tea", class = "food" },
    [4495] = { name = "Gob. Chocolate", class = "food" },
    [4499] = { name = "Iron Bread", class = "food" },
    [4502] = { name = "Marron Glace", class = "food" },
    [4506] = { name = "Mutton Tortilla", class = "food" },
    [4507] = { name = "Rarab Meatball", class = "food" },
    [4510] = { name = "Acorn Cookie", class = "food" },
    [4511] = { name = "Ambrosia", class = "food" },
    [4516] = { name = "Grilled Black Hare", class = "food" },
    [4517] = { name = "Yellow Curry", class = "food" },
    [4518] = { name = "Sheep Jerky", class = "food" },
    [4519] = { name = "Wild Steak", class = "food" },
    [4520] = { name = "Coin Cookie", class = "food" },
    [4521] = { name = "Humpty Soup", class = "food" },
    [4522] = { name = "Jack-o'-Soup", class = "food" },
    [4523] = { name = "Melon Pie +1", class = "food" },
    [4524] = { name = "Royal Tea", class = "food" },
    [4525] = { name = "Pumpkin Pie +1", class = "food" },
    [4532] = { name = "Soft-boiled Egg", class = "food" },
    [4533] = { name = "Delicious Puls", class = "food" },
    [4534] = { name = "Medicinal Gruel", class = "food" },
    [4536] = { name = "Blackened Frog", class = "food" },
    [4537] = { name = "Roast Carp", class = "food" },
    [4538] = { name = "Roast Pipira", class = "food" },
    [4539] = { name = "Goblin Pie", class = "food" },
    [4540] = { name = "Boiled Tuna Head", class = "food" },
    [4542] = { name = "Brain Stew", class = "food" },
    [4543] = { name = "Goblin Mushpot", class = "food" },
    [4544] = { name = "Mushroom Stew", class = "food" },
    [4546] = { name = "Raisin Bread", class = "food" },
    [4547] = { name = "Boiled Cockatrice", class = "food" },
    [4548] = { name = "Coeurl Saute", class = "food" },
    [4549] = { name = "Dragon Soup", class = "food" },
    [4550] = { name = "Bream Risotto", class = "food" },
    [4551] = { name = "Salmon Croute", class = "food" },
    [4552] = { name = "Herb Crawler Eggs", class = "food" },
    [4553] = { name = "Batagreen Saute", class = "food" },
    [4554] = { name = "Shallops Tropicale", class = "food" },
    [4555] = { name = "Windurst Salad", class = "food" },
    [4556] = { name = "Icecap Rolanberry", class = "food" },
    [4557] = { name = "Steamed Catfish", class = "food" },
    [4558] = { name = "Yagudo Drink", class = "food" },
    [4559] = { name = "Herb Quus", class = "food" },
    [4560] = { name = "Vegetable Soup", class = "food" },
    [4561] = { name = "Seafood Stew", class = "food" },
    [4563] = { name = "Pamama Tart", class = "food" },
    [4564] = { name = "Royal Omelette", class = "food" },
    [4568] = { name = "Moon Ball", class = "food" },
    [4569] = { name = "Quadav Stew", class = "food" },
    [4572] = { name = "Beaugr. Saute", class = "food" },
    [4573] = { name = "Steel Bread", class = "food" },
    [4574] = { name = "Meat Chiefkabob", class = "food" },
    [4575] = { name = "Fish Chiefkabob", class = "food" },
    [4576] = { name = "Wizard Cookie", class = "food" },
    [4577] = { name = "Wild Cookie", class = "food" },
    [4578] = { name = "Sausage", class = "food" },
    [4581] = { name = "Blackened Newt", class = "food" },
    [4582] = { name = "Bass Meuniere", class = "food" },
    [4583] = { name = "Salmon Meuniere", class = "food" },
    [4584] = { name = "Flounder Meuniere", class = "food" },
    [4585] = { name = "Broiled Pipira", class = "food" },
    [4586] = { name = "Broiled Carp", class = "food" },
    [4587] = { name = "Broiled Trout", class = "food" },
    [4588] = { name = "Broiled Eel", class = "food" },
    [4589] = { name = "Wild Stew", class = "food" },
    [4590] = { name = "Salmon Rice Ball", class = "food" },
    [4591] = { name = "Pumpernickel", class = "food" },
    [4592] = { name = "Wisdom Soup", class = "food" },
    [4593] = { name = "Rock Cheese", class = "food" },
    [4594] = { name = "Snowy Rolanberry", class = "food" },
    [4595] = { name = "Party Egg", class = "food" },
    [4599] = { name = "Blackened Toad", class = "food" },
    [4600] = { name = "Lucky Egg", class = "food" },
    [4601] = { name = "Sopa Pez Blanco", class = "food" },
    [4603] = { name = "Chamomile Tea", class = "food" },
    [4604] = { name = "Rogue Rice Ball", class = "food" },
    [4605] = { name = "Naval Rice Ball", class = "food" },
    [5142] = { name = "Bison Steak", class = "food" },
    [5143] = { name = "Goblin Stir-Fry", class = "food" },
    [5144] = { name = "Crimson Jelly", class = "food" },
    [5145] = { name = "Fish & Chips", class = "food" },
    [5146] = { name = "Hedgehog Pie", class = "food" },
    [5147] = { name = "Snoll Gelato", class = "food" },
    [5148] = { name = "Squid Sushi", class = "food" },
    [5149] = { name = "Sole Sushi", class = "food" },
    [5150] = { name = "Tuna Sushi", class = "food" },
    [5151] = { name = "Urchin Sushi", class = "food" },
    [5153] = { name = "Fty. Tuna Sushi", class = "food" },
    [5155] = { name = "Sub-zero Gelato", class = "food" },
    [5156] = { name = "Porcupine Pie", class = "food" },
    [5157] = { name = "Marbled Steak", class = "food" },
    [5158] = { name = "Vermillion Jelly", class = "food" },
    [5159] = { name = "Friture Misareaux", class = "food" },
    [5160] = { name = "Urchin Sushi +1", class = "food" },
    [5161] = { name = "Leadafry", class = "food" },
    [5162] = { name = "Squid Sushi +1", class = "food" },
    [5163] = { name = "Sole Sushi +1", class = "food" },
    [5166] = { name = "Coeurl Sub", class = "food" },
    [5167] = { name = "Coeurl Sub +1", class = "food" },
    [5168] = { name = "Bataquiche", class = "food" },
    [5169] = { name = "Bataquiche +1", class = "food" },
    [5170] = { name = "Green Quiche", class = "food" },
    [5171] = { name = "Emerald Quiche", class = "food" },
    [5172] = { name = "Windurst Taco", class = "food" },
    [5173] = { name = "T. Timbers Taco", class = "food" },
    [5174] = { name = "Tavnazian Taco", class = "food" },
    [5175] = { name = "Leremieu Taco", class = "food" },
    [5176] = { name = "Bream Sushi", class = "food" },
    [5177] = { name = "Bream Sushi +1", class = "food" },
    [5178] = { name = "Dorado Sushi", class = "food" },
    [5179] = { name = "Dorado Sushi +1", class = "food" },
    [5180] = { name = "Sophic Stew", class = "food" },
    [5181] = { name = "Tortilla Buena", class = "food" },
    [5182] = { name = "Salty Bretzel", class = "food" },
    [5183] = { name = "Viking Herring", class = "food" },
    [5184] = { name = "Vegan Saute", class = "food" },
    [5185] = { name = "Leremieu Salad", class = "food" },
    [5186] = { name = "Yahata Sushi", class = "food" },
    [5188] = { name = "Peperoncino", class = "food" },
    [5189] = { name = "Vongole Rosso", class = "food" },
    [5190] = { name = "Carbonara", class = "food" },
    [5191] = { name = "Pescatora", class = "food" },
    [5192] = { name = "Boscaiola", class = "food" },
    [5193] = { name = "Nero di Seppia", class = "food" },
    [5194] = { name = "Pomodoro Sauce", class = "food" },
    [5196] = { name = "Buffalo Jerky", class = "food" },
    [5197] = { name = "Peperoncino +1", class = "food" },
    [5198] = { name = "Vongole Rosso +1", class = "food" },
    [5199] = { name = "Carbonara +1", class = "food" },
    [5200] = { name = "Pescatora +1", class = "food" },
    [5201] = { name = "Boscaiola +1", class = "food" },
    [5202] = { name = "Nero Seppia +1", class = "food" },
    [5207] = { name = "Bison Jerky", class = "food" },
    [5210] = { name = "Adamantoise Soup", class = "food" },
    [5211] = { name = "Arrabbiata", class = "food" },
    [5212] = { name = "Arrabbiata +1", class = "food" },
    [5213] = { name = "Melanzane", class = "food" },
    [5214] = { name = "Melanzane +1", class = "food" },
    [5215] = { name = "Tentacle Sushi", class = "food" },
    [5216] = { name = "Tentacle Sushi +1", class = "food" },
    [5218] = { name = "Salmon Roe", class = "food" },
    [5219] = { name = "Ikra Gunkan", class = "food" },
    [5220] = { name = "Ikra Gunkan +1", class = "food" },
    [5221] = { name = "Hmd. Herbal Tea", class = "food" },
    [5222] = { name = "Homemade Stew", class = "food" },
    [5223] = { name = "Hmd. Gelato", class = "food" },
    [5224] = { name = "Hmd. Rice Ball", class = "food" },
    [5225] = { name = "Hmd. Cheese", class = "food" },
    [5226] = { name = "Hmd. Steak", class = "food" },
    [5227] = { name = "Homemade Salad", class = "food" },
    [5228] = { name = "Hmd. Bread", class = "food" },
    [5229] = { name = "Hmd. Risotto", class = "food" },
    [5231] = { name = "Truelove Choco.", class = "food" },
    [5233] = { name = "Cotton Tofu", class = "food" },
    [5238] = { name = "Seafood Stewpot", class = "food" },
    [5239] = { name = "Prm. Sfd. Stewpot", class = "food" },
    [5240] = { name = "Prz. Sfd. Stewpot", class = "food" },
    [5542] = { name = "Gat. aux Fraises", class = "food" },
    [5543] = { name = "Midwinter Dream", class = "food" },
    [5544] = { name = "Crab Stewpot", class = "food" },
    [5545] = { name = "Prm. Crab Stewpot", class = "food" },
    [5546] = { name = "Prz. Crab Stewpot", class = "food" },
    [5547] = { name = "Beef Stewpot", class = "food" },
    [5548] = { name = "Prm. Beef Stewpot", class = "food" },
    [5549] = { name = "Prz. Beef Stewpot", class = "food" },
    [5550] = { name = "Buche au Choco.", class = "food" },
    [5551] = { name = "Sylvan Excursion", class = "food" },
    [5552] = { name = "Black Pudding", class = "food" },
    [5553] = { name = "Dusky Indulgence", class = "food" },
    [5554] = { name = "Squirrel's Delight", class = "food" },
    [5555] = { name = "Flurry Courante", class = "food" },
    [5556] = { name = "Seraph's Kiss", class = "food" },
    [5557] = { name = "Mont Blanc", class = "food" },
    [5558] = { name = "Golden Royale", class = "food" },
    [5559] = { name = "Mille-Feuille", class = "food" },
    [5560] = { name = "Elysian Eclair", class = "food" },
    [5561] = { name = "Moogle Pie", class = "food" },
    [5567] = { name = "Dried Date", class = "food" },
    [5570] = { name = "Chai", class = "food" },
    [5572] = { name = "Irmik Helvasi", class = "food" },
    [5573] = { name = "Irmik Helvasi +1", class = "food" },
    [5574] = { name = "Dried Date +1", class = "food" },
    [5577] = { name = "Sutlac", class = "food" },
    [5578] = { name = "Sutlac +1", class = "food" },
    [5579] = { name = "Yayla Corbasi", class = "food" },
    [5580] = { name = "Yayla Corbasi +1", class = "food" },
    [5582] = { name = "Patlican Salata", class = "food" },
    [5583] = { name = "Patlican Salata +1", class = "food" },
    [5584] = { name = "Ic Pilav", class = "food" },
    [5585] = { name = "Ic Pilav +1", class = "food" },
    [5586] = { name = "Menemen", class = "food" },
    [5587] = { name = "Menemen +1", class = "food" },
    [5588] = { name = "Karni Yarik", class = "food" },
    [5589] = { name = "Karni Yarik +1", class = "food" },
    [5590] = { name = "Balik Sandvici", class = "food" },
    [5591] = { name = "Blk. Sandvici +1", class = "food" },
    [5594] = { name = "Chai +1", class = "food" },
    [5595] = { name = "Nashmau Stew", class = "food" },
    [5596] = { name = "Simit", class = "food" },
    [5597] = { name = "Simit +1", class = "food" },
    [5598] = { name = "Sis Kebabi", class = "food" },
    [5599] = { name = "Sis Kebabi +1", class = "food" },
    [5600] = { name = "Balik Sis", class = "food" },
    [5601] = { name = "Balik Sis +1", class = "food" },
    [5602] = { name = "Hydra Kofte", class = "food" },
    [5603] = { name = "Hydra Kofte +1", class = "food" },
    [5609] = { name = "Hellsteak", class = "food" },
    [5610] = { name = "Hellsteak +1", class = "food" },
    [5611] = { name = "Angler Stewpot", class = "food" },
    [5612] = { name = "Prm. Ang. Stewpot", class = "food" },
    [5613] = { name = "Prz. Ang. Stewpot", class = "food" },
    [5614] = { name = "Konigskuchen", class = "food" },
    [5615] = { name = "Uberkuchen", class = "food" },
    [5616] = { name = "Lebkuchen House", class = "food" },
    [5617] = { name = "Lebkuchen Manse", class = "food" },
    [5618] = { name = "Zoni", class = "food" },
    [5619] = { name = "Zesty Zoni", class = "food" },
    [5620] = { name = "Roast Turkey", class = "food" },
    [5621] = { name = "Candy Ring", class = "food" },
    [5622] = { name = "Candy Cane", class = "food" },
    [5623] = { name = "Tonno Rosso", class = "food" },
    [5624] = { name = "Tonno Rosso +1", class = "food" },
    [5627] = { name = "Yogurt Cake", class = "food" },
    [5628] = { name = "Silken Smile", class = "food" },
    [5633] = { name = "Chocolate Cake", class = "food" },
    [5634] = { name = "Silken Spirit", class = "food" },
    [5635] = { name = "Shrimp Cracker", class = "food" },
    [5636] = { name = "Shr. Cracker +1", class = "food" },
    [5637] = { name = "Pogaca", class = "food" },
    [5638] = { name = "Pogaca +1", class = "food" },
    [5642] = { name = "Cilbir", class = "food" },
    [5643] = { name = "Cibarious Cilbir", class = "food" },
    [5644] = { name = "Jack-o'-Pie", class = "food" },
    [5645] = { name = "Witch Nougat", class = "food" },
    [5647] = { name = "Lik Kabob", class = "food" },
    [5648] = { name = "Grilled Lik", class = "food" },
    [5649] = { name = "Roasted Almonds", class = "food" },
    [5653] = { name = "Cherry Muffin", class = "food" },
    [5654] = { name = "Cherry Muffin +1", class = "food" },
    [5655] = { name = "Coffee Muffin", class = "food" },
    [5656] = { name = "Coff. Muffin +1", class = "food" },
    [5658] = { name = "Ortolana", class = "food" },
    [5659] = { name = "Ortolana +1", class = "food" },
    [5660] = { name = "Pepperoni", class = "food" },
    [5663] = { name = "Salmon Sushi", class = "food" },
    [5664] = { name = "Salmon Sushi +1", class = "food" },
    [5665] = { name = "Fin Sushi", class = "food" },
    [5666] = { name = "Fin Sushi +1", class = "food" },
    [5669] = { name = "Loach Slop", class = "food" },
    [5670] = { name = "Loach Gruel", class = "food" },
    [5671] = { name = "Loach Soup", class = "food" },
    [5672] = { name = "Dried Berry", class = "food" },
    [5673] = { name = "Rolsin", class = "food" },
    [5674] = { name = "Aileen's Delight", class = "food" },
    [5675] = { name = "Withered Berry", class = "food" },
    [5676] = { name = "Mushroom Saute", class = "food" },
    [5677] = { name = "Patriarch Saute", class = "food" },
    [5678] = { name = "Mushroom Salad", class = "food" },
    [5679] = { name = "Cathedral Salad", class = "food" },
    [5681] = { name = "Cupid Chocolate", class = "food" },
    [5683] = { name = "Humpty Dumpty", class = "food" },
    [5684] = { name = "Chalaimbille", class = "food" },
    [5685] = { name = "Rabbit Pie", class = "food" },
    [5686] = { name = "Cheese Sandwich", class = "food" },
    [5687] = { name = "Cheese Sand. +1", class = "food" },
    [5689] = { name = "Meatloaf", class = "food" },
    [5690] = { name = "Meatloaf +1", class = "food" },
    [5691] = { name = "Shrimp Sushi", class = "food" },
    [5692] = { name = "Shrimp Sushi +1", class = "food" },
    [5693] = { name = "Octopus Sushi", class = "food" },
    [5694] = { name = "Octopus Sushi +1", class = "food" },
    [5695] = { name = "Margherita Pizza", class = "food" },
    [5696] = { name = "Marg. Pizza +1", class = "food" },
    [5697] = { name = "Pepperoni Pizza", class = "food" },
    [5698] = { name = "Pepp. Pizza +1", class = "food" },
    [5699] = { name = "Anchovy Pizza", class = "food" },
    [5700] = { name = "Anch. Pizza +1", class = "food" },
    [5701] = { name = "Nopales Salad", class = "food" },
    [5702] = { name = "Nopales Salad +1", class = "food" },
    [5703] = { name = "Uleguerand Milk", class = "food" },
    [5704] = { name = "Angler's Cassoulet", class = "food" },
    [5705] = { name = "Hmd. Salis. Steak", class = "food" },
    [5706] = { name = "Hmd. Carbonara", class = "food" },
    [5707] = { name = "Hmd. Omelette", class = "food" },
    [5708] = { name = "Mihgo Mithkabob", class = "food" },
    [5709] = { name = "Cotton Candy", class = "food" },
    [5710] = { name = "B. Snow Cone", class = "food" },
    [5711] = { name = "K. Snow Cone", class = "food" },
    [5712] = { name = "M. Snow Cone", class = "food" },
    [5713] = { name = "O. Snow Cone", class = "food" },
    [5717] = { name = "M&P Doner Keb.", class = "food" },
    [5718] = { name = "Cream Puff", class = "food" },
    [5719] = { name = "Marinara", class = "food" },
    [5720] = { name = "Marinara +1", class = "food" },
    [5721] = { name = "Crab Sushi", class = "food" },
    [5722] = { name = "Crab Sushi +1", class = "food" },
    [5727] = { name = "Zaru Soba", class = "food" },
    [5728] = { name = "Zaru Soba +1", class = "food" },
    [5729] = { name = "Bavarois", class = "food" },
    [5730] = { name = "Bavarois +1", class = "food" },
    [5731] = { name = "Ratatouille", class = "food" },
    [5732] = { name = "Ratatouille +1", class = "food" },
    [5737] = { name = "Salted Hare", class = "food" },
    [5738] = { name = "Sweet Lizard", class = "food" },
    [5739] = { name = "Honeyed Egg", class = "food" },
    [5743] = { name = "Marinara Pizza", class = "food" },
    [5744] = { name = "Marinara Pizza +1", class = "food" },
    [5745] = { name = "Cherry Bavarois", class = "food" },
    [5746] = { name = "Cherry Bavarois +1", class = "food" },
    [5747] = { name = "Marinara Sauce", class = "food" },
    [5750] = { name = "Goulash", class = "food" },
    [5751] = { name = "Goulash +1", class = "food" },
    [5752] = { name = "Pot-au-feu", class = "food" },
    [5753] = { name = "Pot-au-feu +1", class = "food" },
    [5756] = { name = "Green Curry Bun", class = "food" },
    [5757] = { name = "Ylw. Curry Bun", class = "food" },
    [5758] = { name = "Black Curry Bun", class = "food" },
    [5759] = { name = "Red Curry Bun", class = "food" },
    [5760] = { name = "Kohlrouladen", class = "food" },
    [5761] = { name = "Kohlrouladen +1", class = "food" },
    [5762] = { name = "G. Curry Bun +1", class = "food" },
    [5763] = { name = "Y. Curry Bun +1", class = "food" },
    [5764] = { name = "B. Curry Bun +1", class = "food" },
    [5765] = { name = "R. Curry Bun +1", class = "food" },
    [5766] = { name = "Butter Crepe", class = "food" },
    [5767] = { name = "Crepe Delice", class = "food" },
    [5771] = { name = "Ham & Ch. Crepe", class = "food" },
    [5772] = { name = "Crepe Paysanne", class = "food" },
    [5773] = { name = "Mushroom Crepe", class = "food" },
    [5774] = { name = "Crepe Forestiere", class = "food" },
    [5775] = { name = "Chocolate Crepe", class = "food" },
    [5776] = { name = "Crepe Caprice", class = "food" },
    [5777] = { name = "Pear Crepe", class = "food" },
    [5778] = { name = "Crepe B. Helene", class = "food" },
    [5779] = { name = "Cherry Macaron", class = "crafting" },
    [5780] = { name = "Coffee Macaron", class = "crafting" },
    [5781] = { name = "Kitron Macaron", class = "crafting" },
    [5782] = { name = "Sugar Rusk", class = "crafting" },
    [5783] = { name = "Chocolate Rusk", class = "crafting" },
    [5784] = { name = "Coconut Rusk", class = "crafting" },
    [5859] = { name = "Glk. Sausage +1", class = "food" },
    [5860] = { name = "Glk. Sausage +2", class = "food" },
    [5861] = { name = "Glk. Sausage +3", class = "food" },
    [5862] = { name = "Glk. Sausage -1", class = "food" },
    [5885] = { name = "Saltena", class = "food" },
    [5886] = { name = "Elshena", class = "food" },
    [5887] = { name = "Montagna", class = "food" },
    [5888] = { name = "Maringna", class = "food" },
    [5889] = { name = "Stuffed Pitaru", class = "food" },
    [5890] = { name = "Poultry Pitaru", class = "food" },
    [5891] = { name = "Seafood Pitaru", class = "food" },
    [5892] = { name = "B.E.W. Pitaru", class = "food" },
    [5893] = { name = "Marine Stewpot", class = "food" },
    [5894] = { name = "Prm. Mn. Stewpot", class = "food" },
    [5922] = { name = "Walnut Cookie", class = "food" },
    [5923] = { name = "Juglan Jumble", class = "food" },
    [5924] = { name = "S. Salis. Steak", class = "food" },
    [5925] = { name = "C. Salis. Steak", class = "food" },
    [5926] = { name = "Date Tea", class = "food" },
    [5927] = { name = "Caravan Tea", class = "food" },
    [5928] = { name = "Himesama R. Ball", class = "food" },
    [5929] = { name = "Ojo Rice Ball", class = "food" },
    [5930] = { name = "Sprightly Soup", class = "food" },
    [5931] = { name = "Shimmy Soup", class = "food" },
    [5932] = { name = "Kitron Juice", class = "food" },
    [5933] = { name = "D. Fruit au Lait", class = "food" },
    [5934] = { name = "Chocobiscuit", class = "food" },
    [5935] = { name = "Moogurt", class = "food" },
    [5940] = { name = "Trail Cookie", class = "food" },
    [5941] = { name = "Campfire Choco", class = "food" },
    [5942] = { name = "Cascade Candy", class = "food" },
    [5943] = { name = "Smoked Mackerel", class = "food" },
    [5968] = { name = "Seafood Paella", class = "food" },
    [5969] = { name = "Piscator's Paella", class = "food" },
    [5970] = { name = "Mushroom Paella", class = "food" },
    [5971] = { name = "Mush. Paella +1", class = "food" },
    [5972] = { name = "Beef Paella", class = "food" },
    [5973] = { name = "Beef Paella +1", class = "food" },
    [5974] = { name = "Barnacle Paella", class = "food" },
    [5975] = { name = "Flapano's Paella", class = "food" },
    [5976] = { name = "Ulbuconut Milk", class = "food" },
    [5977] = { name = "Ulbuconut Milk +1", class = "food" },
    [5978] = { name = "Felicifruit Gelatin", class = "food" },
    [5979] = { name = "Dulcet Panettones", class = "food" },
    [5980] = { name = "Boiled Barnacles", class = "food" },
    [5981] = { name = "Bld. Barnacles +1", class = "food" },
    [5982] = { name = "Senroh Skewer", class = "food" },
    [5983] = { name = "Piscator's Skewer", class = "food" },
    [5998] = { name = "Adoulinian Soup", class = "food" },
    [5999] = { name = "Adoulinian Soup +1", class = "food" },
    [6009] = { name = "Mog Pudding", class = "food" },
    [6010] = { name = "Sakura Biscuit", class = "food" },
    [6063] = { name = "Fruit Parfait", class = "food" },
    [6064] = { name = "Queen's Crown", class = "food" },
    [6065] = { name = "Tiny Macaron", class = "crafting" },
    [6066] = { name = "Tiny Rusk", class = "crafting" },
    [6069] = { name = "Riverfin Soup", class = "food" },
    [6070] = { name = "Oceanfin Soup", class = "food" },
    [6071] = { name = "Magma Steak", class = "food" },
    [6072] = { name = "Magma Steak +1", class = "food" },
    [6211] = { name = "Marinara Slice", class = "food" },
    [6212] = { name = "Marinara Slice +1", class = "food" },
    [6213] = { name = "Margherita Slice", class = "food" },
    [6214] = { name = "Marg. Slice +1", class = "food" },
    [6215] = { name = "Pepperoni Slice", class = "food" },
    [6216] = { name = "Pepp. Slice +1", class = "food" },
    [6217] = { name = "Anchovy Slice", class = "food" },
    [6218] = { name = "Anch. Slice +1", class = "food" },
    [6219] = { name = "Warthog Stewpot", class = "food" },
    [6220] = { name = "Prm. Wt. Stewpot", class = "food" },
    [6221] = { name = "Prz. Wt. Stewpot", class = "food" },
    [6223] = { name = "C. Snow Cone", class = "food" },
    [6224] = { name = "A. Snow Cone", class = "food" },
    [6225] = { name = "C. Coalescence", class = "food" },
    [6226] = { name = "Pixioche", class = "food" },
    [6257] = { name = "Jungle Nectar", class = "food" },
    [6258] = { name = "Shiromochi", class = "food" },
    [6259] = { name = "Shiromochi +1", class = "food" },
    [6260] = { name = "Akamochi", class = "food" },
    [6261] = { name = "Akamochi +1", class = "food" },
    [6262] = { name = "Kusamochi", class = "food" },
    [6263] = { name = "Kusamochi +1", class = "food" },
    [6272] = { name = "Fried Popoto", class = "food" },
    [6273] = { name = "Fried Popoto +1", class = "food" },
    [6274] = { name = "Pukatrice Egg", class = "food" },
    [6275] = { name = "Pukatrice Egg +1", class = "food" },
    [6276] = { name = "D.-fried Shrimp", class = "food" },
    [6277] = { name = "D.-fr. Shrimp +1", class = "food" },
    [6339] = { name = "Rolan. Daifuku", class = "food" },
    [6340] = { name = "Rolan. Daifuku +1", class = "food" },
    [6341] = { name = "Bean Daifuku", class = "food" },
    [6342] = { name = "Bean Daifuku +1", class = "food" },
    [6343] = { name = "Grape Daifuku", class = "food" },
    [6344] = { name = "Grape Daifuku +1", class = "food" },
    [6394] = { name = "Pork Cutlet", class = "food" },
    [6395] = { name = "Pork Cutlet +1", class = "food" },
    [6396] = { name = "Cutlet Sandwich", class = "food" },
    [6397] = { name = "Cutlet Sandwich +1", class = "food" },
    [6406] = { name = "Pork Cutlet Bowl", class = "food" },
    [6407] = { name = "Pork Cutlet Bowl +1", class = "food" },
    [6458] = { name = "Soy Ramen", class = "food" },
    [6459] = { name = "Soy Ramen +1", class = "food" },
    [6460] = { name = "Miso Ramen", class = "food" },
    [6461] = { name = "Miso Ramen +1", class = "food" },
    [6462] = { name = "Salt Ramen", class = "food" },
    [6463] = { name = "Salt Ramen +1", class = "food" },
    [6464] = { name = "Behemoth Steak", class = "food" },
    [6465] = { name = "Behe. Steak +1", class = "food" },
    [6466] = { name = "Miso Soup", class = "food" },
    [6467] = { name = "Miso Soup +1", class = "food" },
    [6468] = { name = "Sublime Sushi", class = "food" },
    [6469] = { name = "Sublime Sushi +1", class = "food" },
    [6470] = { name = "Oden", class = "food" },
    [6471] = { name = "Oden +1", class = "food" },
    [6538] = { name = "Altana's Repast", class = "food" },
    [6539] = { name = "Altana's Repast +1", class = "food" },
    [6540] = { name = "Altana's Repast +2", class = "food" },
    [6565] = { name = "Per. Snow Cone", class = "food" },
    [6567] = { name = "Tropical Crepe", class = "food" },
    [6568] = { name = "Crepe des Rois", class = "food" },
    [6575] = { name = "Cheesestk. Sand.", class = "food" },
    [6576] = { name = "Rol. Turkey", class = "food" },
    [6577] = { name = "Clam Chowder", class = "food" },
    [6578] = { name = "Popoto Gratin", class = "food" },
    [6579] = { name = "Behemoth Sand.", class = "food" },
    [6580] = { name = "Rustic Fish", class = "food" },
    [6581] = { name = "Cornbread", class = "food" },
    [6582] = { name = "W. Snow Cone", class = "food" },
    [6583] = { name = "Salted Dfly. Trout", class = "food" },
    [6584] = { name = "Grilled Dfly. Trout", class = "food" },
    [6599] = { name = "Egg Sandwich", class = "food" },
    [6600] = { name = "Egg Sand. +1", class = "food" },
    [6601] = { name = "Om. Sandwich", class = "food" },
    [6602] = { name = "Om. Sand. +1", class = "food" },
    [6609] = { name = "Popo. con Queso", class = "food" },
    [6610] = { name = "Popo. con Que. +1", class = "food" },
    [6611] = { name = "Seafood Gratin", class = "food" },
    [6612] = { name = "Sea. Gratin +1", class = "food" },
    [6686] = { name = "Gyudon", class = "food" },
    [6687] = { name = "Gyudon +1", class = "food" },
    [17016] = { name = "Pet Food Alpha", class = "petfood" },
    [17017] = { name = "Pet Food Beta", class = "petfood" },
    [17018] = { name = "Pet Fd. Gamma", class = "petfood" },
    [17019] = { name = "Pet Food Delta", class = "petfood" },
    [17020] = { name = "Pet Fd. Epsilon", class = "petfood" },
    [17021] = { name = "Pet Food Zeta", class = "petfood" },
    [17022] = { name = "Pet Food Eta", class = "petfood" },
    [17023] = { name = "Pet Food Theta", class = "petfood" },
}
